"""Canonical CSV column order for generated tables."""

TABLE_COLUMNS: dict[str, list[str]] = {
    "customers": [
        "customer_id",
        "customer_name",
        "customer_segment",
        "industry",
        "contract_start_date",
        "contract_end_date",
        "default_sla_hours",
        "payment_terms_days",
        "is_active",
    ],
    "routes": [
        "route_id",
        "route_code",
        "origin_region",
        "destination_region",
        "standard_distance_km",
        "standard_transit_hours",
        "route_class",
        "is_active",
    ],
    "drivers": [
        "driver_id",
        "driver_code",
        "hire_date",
        "experience_years",
        "license_class",
        "home_region",
        "employment_status",
    ],
    "vehicles": [
        "vehicle_id",
        "vehicle_code",
        "vehicle_type",
        "capacity_kg",
        "manufacture_year",
        "fuel_type",
        "fuel_consumption_l_100km",
        "odometer_at_observation_start_km",
        "home_region",
        "service_status",
    ],
    "orders": [
        "order_id",
        "customer_id",
        "route_id",
        "created_at",
        "requested_pickup_at",
        "promised_delivery_at",
        "cargo_type",
        "cargo_weight_kg",
        "distance_planned_km",
        "quoted_revenue",
        "priority",
        "order_status",
    ],
    "deliveries": [
        "delivery_id",
        "order_id",
        "driver_id",
        "vehicle_id",
        "planned_departure_at",
        "actual_departure_at",
        "actual_delivery_at",
        "distance_actual_km",
        "delivery_status",
        "fuel_cost",
        "driver_cost",
        "toll_cost",
        "maintenance_allocated_cost",
        "other_cost",
        "penalty_amount",
    ],
    "route_events": [
        "event_id",
        "delivery_id",
        "event_at",
        "event_end_at",
        "event_type",
        "severity",
        "delay_minutes",
        "extra_cost",
        "region",
        "notes_code",
    ],
    "maintenance": [
        "maintenance_id",
        "vehicle_id",
        "maintenance_type",
        "started_at",
        "completed_at",
        "odometer_km",
        "cost_amount",
        "downtime_hours",
        "issue_category",
        "maintenance_status",
    ],
}

PRIMARY_KEYS: dict[str, str] = {
    "customers": "customer_id",
    "routes": "route_id",
    "drivers": "driver_id",
    "vehicles": "vehicle_id",
    "orders": "order_id",
    "deliveries": "delivery_id",
    "route_events": "event_id",
    "maintenance": "maintenance_id",
}
