# ruff: noqa: E501
"""Fixed recommendation cards derived from the frozen evidence rules."""

from __future__ import annotations

from typing import Any

from delivery_pulse.recommendations.models import Recommendation
from delivery_pulse.recommendations.prioritization import (
    priority_category,
    priority_score,
)


def build_recommendations(
    hypotheses: dict[str, dict[str, object]],
) -> tuple[Recommendation, ...]:
    """Build R1–R6 without estimating new statistical models."""
    del hypotheses  # Status integrity is validated before this deterministic catalog.
    specs: list[dict[str, Any]] = [
        dict(
            recommendation_id="R1",
            title="Pilot express-операций",
            business_area="operations_and_commercial",
            problem_statement="Express связан с повышенным риском опоздания.",
            evidence_level="strong_observational_evidence",
            supporting_hypotheses=("H2",),
            supporting_metrics=("express_otd", "p90_delay", "penalty_amount"),
            observed_effect="Adjusted late-risk difference +6.22 pp; OR 15.93.",
            uncertainty="Наблюдательная связь; priority может отражать состав процесса.",
            recommended_action="Проверить SLA, раннее назначение ресурсов, маршрутный буфер и риск-тариф в ограниченном pilot.",
            action_type="pilot",
            expected_direction="Снижение express lateness без ухудшения standard OTD.",
            expected_benefit="Меньше опозданий и штрафов при сохранении маржи.",
            implementation_effort=3,
            operational_risk=3,
            confidence=5,
            business_impact=5,
            urgency=5,
            reversibility=4,
            owner_role="operations_lead",
            target_kpis=(
                "express_otd",
                "late_express_count",
                "p90_delay",
                "penalty_amount",
                "group_margin",
            ),
            guardrail_metrics=("standard_otd", "failed_rate", "safety_incidents"),
            pilot_design="Сравнить выбранные рискованные маршруты с сопоставимыми маршрутами; 8–12 недель, минимум 1 000 express-доставок.",
            review_period="через 8–12 недель pilot",
            stop_conditions="Остановить при ухудшении standard OTD, безопасности или group margin сверх заранее заданного guardrail.",
            limitations="OR не является причинным множителем и не используется как ожидаемое снижение риска.",
        ),
        dict(
            recommendation_id="R2",
            title="Pilot управления поломками",
            business_area="fleet_operations",
            problem_statement="Breakdown концентрирует убыточные доставки и тяжёлые потери.",
            evidence_level="strong_observational_evidence",
            supporting_hypotheses=("H3",),
            supporting_metrics=(
                "breakdown_loss_rate",
                "delivery_profit",
                "downtime_hours",
            ),
            observed_effect="Adjusted loss-risk difference +83.69 pp; profit difference −69,870 RUB (p1–p99: −53,082).",
            uncertainty="Экстремальный OR нестабилен как величина причинного эффекта.",
            recommended_action="Проверить резервный автомобиль, SLA реакции, эвакуацию, замену транспорта и контроль event cost.",
            action_type="pilot",
            expected_direction="Снижение убытка и recovery time при breakdown.",
            expected_benefit="Сокращение тяжёлого хвоста убытков и downtime.",
            implementation_effort=4,
            operational_risk=3,
            confidence=5,
            business_impact=5,
            urgency=5,
            reversibility=4,
            owner_role="fleet_operations_lead",
            target_kpis=(
                "breakdown_loss_rate",
                "mean_breakdown_loss",
                "downtime_hours",
                "recovery_time",
                "breakdowns_per_10k_km",
                "fleet_availability",
            ),
            guardrail_metrics=(
                "safety_incidents",
                "reserve_vehicle_utilization",
                "total_fleet_cost",
            ),
            pilot_design="На наиболее затратных маршрутах сравнить усиленный response с обычным процессом; 8–12 недель и минимум 100 breakdown-событий.",
            review_period="через 8–12 недель pilot",
            stop_conditions="Остановить при ухудшении безопасности, доступности парка или росте полной стоимости выше лимита.",
            limitations="H4 не позволяет приписывать эффект изменению интервалов планового ТО.",
        ),
        dict(
            recommendation_id="R3",
            title="Коммерческий review клиентской прибыльности",
            business_area="commercial",
            problem_statement="Межклиентские различия прибыли сохраняются после контроля mix.",
            evidence_level="strong_observational_evidence",
            supporting_hypotheses=("H5",),
            supporting_metrics=("adjusted_profit", "group_margin", "loss_amount"),
            observed_effect="165 клиентов прошли порог; диапазон adjusted effects 23,963 RUB.",
            uncertainty="Fixed effects без hierarchical shrinkage; малые клиенты не ранжируются.",
            recommended_action="Pilot review тарифов, SLA, штрафов, route mix, express share и минимальной цены только для клиентов достаточного объёма.",
            action_type="pilot",
            expected_direction="Рост скорректированной прибыли без неприемлемой потери объёма.",
            expected_benefit="Более устойчивые договорные условия и снижение loss amount.",
            implementation_effort=3,
            operational_risk=4,
            confidence=4,
            business_impact=3,
            urgency=2,
            reversibility=3,
            owner_role="commercial_lead",
            target_kpis=(
                "adjusted_profit",
                "group_margin",
                "loss_amount",
                "retention",
                "orders_count",
            ),
            guardrail_metrics=(
                "retention",
                "orders_count",
                "rejection_rate",
                "service_level",
            ),
            pilot_design="Review ограниченной группы крупных клиентов против сопоставимой группы; один договорный цикл, минимум 90 доставок на клиента.",
            review_period="после одного договорного цикла",
            stop_conditions="Остановить расширение при существенном падении retention, объёма или SLA.",
            limitations="Нескорректированная маржа не является достаточным основанием для решения по клиенту.",
        ),
        dict(
            recommendation_id="R4",
            title="Измерение длительности погрузки",
            business_area="terminal_operations",
            problem_statement="Бинарный loading_delay не поддержан, но длительность дала secondary signal.",
            evidence_level="moderate_or_secondary_evidence",
            supporting_hypotheses=("H1",),
            supporting_metrics=("loading_delay_minutes", "late_rate"),
            observed_effect="Primary adjusted risk difference +0.12 pp, CI crosses zero; duration sensitivity OR 1.175.",
            uncertainty="Secondary specification; наличие события само по себе не связано устойчиво.",
            recommended_action="Ввести мониторинг длительности, пороги эскалации и небольшой pilot уведомлений.",
            action_type="pilot",
            expected_direction="Сокращение длинных простоев; эффект на OTD требует проверки.",
            expected_benefit="Более точное измерение узкого места и проверяемый response.",
            implementation_effort=2,
            operational_risk=2,
            confidence=3,
            business_impact=3,
            urgency=3,
            reversibility=5,
            owner_role="terminal_operations_lead",
            target_kpis=("loading_delay_minutes", "p90_loading_delay", "late_rate"),
            guardrail_metrics=(
                "loading_quality_incidents",
                "staff_overtime",
                "failed_rate",
            ),
            pilot_design="Случайно или квазиэкспериментально включить alerts на части площадок; 8 недель, минимум 1 000 доставок в группе.",
            review_period="через 8 недель",
            stop_conditions="Остановить при росте ошибок погрузки, overtime или отсутствии измеримого изменения длительности.",
            limitations="Не масштабировать программу только по наличию loading_delay.",
        ),
        dict(
            recommendation_id="R5",
            title="Улучшение данных об обслуживании",
            business_area="fleet_data",
            problem_statement="Текущая модель H4 не даёт устойчивой оценки профилактики.",
            evidence_level="insufficient_evidence",
            supporting_hypotheses=("H4",),
            supporting_metrics=(
                "km_since_last_maintenance",
                "days_since_last_maintenance",
                "breakdown_count",
            ),
            observed_effect="IRR имеет практически неограниченный CI; результат inconclusive.",
            uncertainty="Редкие события и неустойчивый коэффициент.",
            recommended_action="Не менять интервалы ТО; фиксировать pre-trip condition, дни/км после ТО и разделять scheduled maintenance и repair.",
            action_type="collect_more_data",
            expected_direction="Повышение пригодности следующего longitudinal-анализа.",
            expected_benefit="Надёжное решение об интервалах ТО после накопления периодов.",
            implementation_effort=2,
            operational_risk=1,
            confidence=2,
            business_impact=4,
            urgency=3,
            reversibility=5,
            owner_role="fleet_data_owner",
            target_kpis=(
                "maintenance_data_completeness",
                "pre_trip_condition_coverage",
                "exposure_months",
            ),
            guardrail_metrics=("maintenance_compliance", "safety_incidents"),
            pilot_design="Не процессный pilot: минимум ещё 12 месяцев наблюдений с полными lagged exposures.",
            review_period="после накопления 12 дополнительных месяцев",
            stop_conditions="Не переходить к оценке, пока полнота ключевых lagged-полей ниже 95%.",
            limitations="Repair после breakdown нельзя считать профилактической экспозицией.",
        ),
        dict(
            recommendation_id="R6",
            title="Сохранить лимиты перегруза и накапливать выборку",
            business_area="safety_and_operations",
            problem_statement="206 overload и 6 losses недостаточны для segment interaction.",
            evidence_level="insufficient_evidence",
            supporting_hypotheses=("H6",),
            supporting_metrics=("capacity_utilization", "overload_count", "loss_count"),
            observed_effect="Interaction не оценивался; Fisher sensitivity не меняет inconclusive.",
            uncertainty="Недостаточные ячейки по vehicle type и route class.",
            recommended_action="Сохранить ограничения безопасности, не делать финансовый вывод, мониторить массу/ёмкость и заранее накопить достаточные ячейки.",
            action_type="do_not_act_yet",
            expected_direction="Безопасное накопление доказательств без изменения политики.",
            expected_benefit="Предотвращение решения на слабой выборке.",
            implementation_effort=1,
            operational_risk=1,
            confidence=1,
            business_impact=4,
            urgency=2,
            reversibility=5,
            owner_role="safety_lead",
            target_kpis=(
                "overload_count",
                "capacity_data_completeness",
                "segment_cell_size",
            ),
            guardrail_metrics=("safety_incidents", "capacity_utilization_max"),
            pilot_design="Pilot процесса не проводится; повторный анализ только после ≥100 overload и ≥20 outcomes в каждом заранее заданном сегменте.",
            review_period="после достижения минимальных ячеек",
            stop_conditions="Не ослаблять safety limits независимо от промежуточной финансовой метрики.",
            limitations="Нельзя рекомендовать запрет или разрешение перегруза по текущей модели.",
        ),
    ]
    cards: list[Recommendation] = []
    for spec in specs:
        score = priority_score(
            business_impact=spec.pop("business_impact"),
            evidence=spec["evidence_level"],
            confidence=spec["confidence"],
            urgency=spec.pop("urgency"),
            reversibility=spec.pop("reversibility"),
            implementation_effort=spec["implementation_effort"],
            operational_risk=spec["operational_risk"],
        )
        priority = priority_category(score, spec["evidence_level"], spec["action_type"])
        cards.append(Recommendation(**spec, priority_score=score, priority=priority))
    return tuple(cards)
